spring.datasource.username=ccadmin
spring.datasource.password=message
spring.datasource.url=jdbc:postgresql://localhost:8922/message_db
#---------------------------Spring-----------------------------------#
spring.application.name=Campus Connect - Message API
spring.security.user.name=ccmsg
spring.security.user.password=ccmsg
spring.jackson.default-property-inclusion=non_null
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.port=8081
#---------------------------JPA | Flyway-----------------------------------#
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-migration-naming=true
#---------------------------Environment variables---------------------------#
#jwt.auth.converter.resource-id=${JWT_ID: msg_oauth}
#jwt.auth.converter.principle-atribute=${JWT_PREFER: preferred_username}
api.security.token.secret=${API_SECRET: de367b940e6de153fae1ee72b7b95ab8}
api.security.issuer=${API_ISSUER: c8170b1d113e26e873092e2d86395598}
api.url=${API_URL:http://localhost:8081}
logging.level.org.springframework=INFO
#---------------------------Swagger----------------------------------------#
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=openapi_3_1
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=swagger-ui.html
springdoc.swagger-ui.operationsSorter=Alpha
server.forward-headers-strategy=framework
#Files
image.maxWidth=${IMAGE-maxWidth:3840}
image.maxHeight=${IMAGE-maxHeight:2160}
server.storagePath=/opt/events-files
#Mail local
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=59651a259558d2
spring.mail.password=7e80ab69d54bf5
front.url=${FRONT_URL:http://localhost:4200/auth/login}

