#---------------------------Database---------------------------------------#
spring.datasource.url=jdbc:postgresql://dpg-cr9j3brv2p9s73b91qfg-a.oregon-postgres.render.com/message_db_m0n5
spring.datasource.username=ccadmin
spring.datasource.password=KKGeI7PquzccFKJVpFm4bDHzOMDgc2xh
#Files
folder.img=${FOLDER_IMG:Imagens}
folder.files=${FOLDER_FILES:Files}
drive.url=${DRIVE_URL:https://drive.usercontent.google.com/download?id=}
cloudinary.url=${CLOUDINARY_URL:cloudinary://391979215723458:LZYSfsbFNIxo_vEKI6foI2U_n3s@dgz08cahv}