#---------------------------Database---------------------------------------#
spring.datasource.url=jdbc:postgresql://dpg-cr9j3brv2p9s73b91qfg-a.oregon-postgres.render.com/message_db_m0n5
spring.datasource.username=ccadmin
spring.datasource.password=KKGeI7PquzccFKJVpFm4bDHzOMDgc2xh
#Files
folder.img=${FOLDER_IMG:1L3F_kAzKJym1OStNllQtHDeoK61nTYY2}
folder.files=${FOLDER_FILES:1K5YlSWUkC8-l53GK8Rtzj6TWwLuOun8s}
drive.url=${DRIVE_URL:https://drive.google.com/uc?export=view&id=}
