
#Files
folder.img=${FOLDER_IMG:Imagens}
folder.files=${FOLDER_FILES:Files}
#drive.url=${DRIVE_URL:https://drive.usercontent.google.com/download?id=}
cloudinary.url=${CLOUDINARY_URL:cloudinary://391979215723458:LZYSfsbFNIxo_vEKI6foI2U_n3s@dgz08cahv}

drive.folder.img=${FOLDER_IMG:1L3F_kAzKJym1OStNllQtHDeoK61nTYY2}
drive.folder.files=${FOLDER_FILES:1K5YlSWUkC8-l53GK8Rtzj6TWwLuOun8s}
drive.url=${DRIVE_URL:https://drive.google.com/uc?export=view&id=}
server.port=8081
#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=camconnectmsg@gmail.com
spring.mail.password=rvrx kosf ewgi nvol
spring.mail.properties.mail.smtp.auth=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=utf-8